"""initial_schema

Revision ID: fa2e02e5c03e
Revises: 
Create Date: 2026-02-25 05:11:40.444739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa2e02e5c03e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('blocked_by', sa.BigInteger(), nullable=True),
    sa.Column('blocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('unblocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blacklist_entity_id'), 'blacklist', ['entity_id'], unique=False)
    op.create_table('bot_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_title', sa.String(length=255), nullable=True),
    sa.Column('invite_link', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('installed_by', sa.BigInteger(), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_chat_id'), 'channels', ['chat_id'], unique=True)
    op.create_table('chat_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_type', sa.String(length=16), nullable=False),
    sa.Column('music_enabled', sa.Boolean(), nullable=False),
    sa.Column('video_enabled', sa.Boolean(), nullable=False),
    sa.Column('audio_enabled', sa.Boolean(), nullable=False),
    sa.Column('file_enabled', sa.Boolean(), nullable=False),
    sa.Column('soundcloud_enabled', sa.Boolean(), nullable=False),
    sa.Column('spotify_enabled', sa.Boolean(), nullable=False),
    sa.Column('inline_enabled', sa.Boolean(), nullable=False),
    sa.Column('force_join_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_leave_enabled', sa.Boolean(), nullable=False),
    sa.Column('anti_spam_enabled', sa.Boolean(), nullable=False),
    sa.Column('filter_enabled', sa.Boolean(), nullable=False),
    sa.Column('security_call_enabled', sa.Boolean(), nullable=False),
    sa.Column('download_enabled', sa.Boolean(), nullable=False),
    sa.Column('lyrics_enabled', sa.Boolean(), nullable=False),
    sa.Column('announce_enabled', sa.Boolean(), nullable=False),
    sa.Column('buttons_enabled', sa.Boolean(), nullable=False),
    sa.Column('vote_skip_enabled', sa.Boolean(), nullable=False),
    sa.Column('smart_radio_enabled', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'chat_type', name='uq_chat_settings_chat')
    )
    op.create_index(op.f('ix_chat_settings_chat_id'), 'chat_settings', ['chat_id'], unique=False)
    op.create_table('credit_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_type', sa.String(length=16), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('amount_days', sa.Integer(), nullable=False),
    sa.Column('operated_by', sa.BigInteger(), nullable=True),
    sa.Column('operated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_history_chat_id'), 'credit_history', ['chat_id'], unique=False)
    op.create_index(op.f('ix_credit_history_invoice_id'), 'credit_history', ['invoice_id'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('stream_url', sa.String(length=2048), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=16), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_table('filter_words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('added_by', sa.BigInteger(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filter_words_word'), 'filter_words', ['word'], unique=True)
    op.create_table('force_join_channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_username', sa.String(length=128), nullable=True),
    sa.Column('invite_link', sa.String(length=512), nullable=True),
    sa.Column('added_by', sa.BigInteger(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_force_join_channels_channel_id'), 'force_join_channels', ['channel_id'], unique=True)
    op.create_table('free_install_whitelist',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_type', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('group_credits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_type', sa.String(length=16), nullable=False),
    sa.Column('credit_days', sa.Integer(), nullable=False),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('charged_by', sa.BigInteger(), nullable=True),
    sa.Column('total_charged', sa.Integer(), nullable=False),
    sa.Column('is_trial', sa.Boolean(), nullable=False),
    sa.Column('trial_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_expire_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'chat_type', name='uq_group_credits_chat')
    )
    op.create_index(op.f('ix_group_credits_chat_id'), 'group_credits', ['chat_id'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_title', sa.String(length=255), nullable=True),
    sa.Column('invite_link', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('installed_by', sa.BigInteger(), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_chat_id'), 'groups', ['chat_id'], unique=True)
    op.create_table('helper_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('session_string_enc', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('max_concurrent_calls', sa.Integer(), nullable=False),
    sa.Column('current_active_calls', sa.Integer(), nullable=False),
    sa.Column('max_joins_per_hour', sa.Integer(), nullable=False),
    sa.Column('joins_last_hour', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('banned_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_helper_accounts_phone'), 'helper_accounts', ['phone'], unique=True)
    op.create_table('install_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_title', sa.String(length=255), nullable=True),
    sa.Column('chat_type', sa.String(length=16), nullable=False),
    sa.Column('triggered_by', sa.BigInteger(), nullable=True),
    sa.Column('sudo_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_install_logs_chat_id'), 'install_logs', ['chat_id'], unique=False)
    op.create_table('install_policy_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_mode', sa.String(length=32), nullable=False),
    sa.Column('trial_days', sa.Integer(), nullable=False),
    sa.Column('charge_on_install', sa.Boolean(), nullable=False),
    sa.Column('group_install_fee_irr', sa.BigInteger(), nullable=False),
    sa.Column('chan_install_fee_irr', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_type', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('issued_by', sa.BigInteger(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_chat_id'), 'invoices', ['chat_id'], unique=False)
    op.create_table('music_admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('promoted_by', sa.BigInteger(), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'user_id', name='uq_music_admin_chat_user')
    )
    op.create_index(op.f('ix_music_admins_chat_id'), 'music_admins', ['chat_id'], unique=False)
    op.create_index(op.f('ix_music_admins_user_id'), 'music_admins', ['user_id'], unique=False)
    op.create_table('owner_sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False),
    sa.Column('sudo_user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_scope', sa.String(length=64), nullable=True),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('price_irr', sa.BigInteger(), nullable=False),
    sa.Column('payment_ref', sa.String(length=256), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owner_sales_owner_user_id'), 'owner_sales', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_owner_sales_sudo_user_id'), 'owner_sales', ['sudo_user_id'], unique=False)
    op.create_table('owners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('added_by', sa.BigInteger(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owners_user_id'), 'owners', ['user_id'], unique=True)
    op.create_table('player_owners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('promoted_by', sa.BigInteger(), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'user_id', name='uq_player_owner_chat_user')
    )
    op.create_index(op.f('ix_player_owners_chat_id'), 'player_owners', ['chat_id'], unique=False)
    op.create_index(op.f('ix_player_owners_user_id'), 'player_owners', ['user_id'], unique=False)
    op.create_table('player_vips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('promoted_by', sa.BigInteger(), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'user_id', name='uq_player_vip_chat_user')
    )
    op.create_index(op.f('ix_player_vips_chat_id'), 'player_vips', ['chat_id'], unique=False)
    op.create_index(op.f('ix_player_vips_user_id'), 'player_vips', ['user_id'], unique=False)
    op.create_table('playlists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('stream_url', sa.String(length=2048), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=16), nullable=False),
    sa.Column('added_by', sa.BigInteger(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlists_chat_id'), 'playlists', ['chat_id'], unique=False)
    op.create_table('sudo_bulk_invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sudo_user_id', sa.BigInteger(), nullable=False),
    sa.Column('amount_toman', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('issued_by', sa.BigInteger(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sudo_bulk_invoices_sudo_user_id'), 'sudo_bulk_invoices', ['sudo_user_id'], unique=False)
    op.create_table('sudos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('added_by', sa.BigInteger(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sudo_link', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_installs', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sudos_user_id'), 'sudos', ['user_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('banned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('banned_by', sa.BigInteger(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_table('video_admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('promoted_by', sa.BigInteger(), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'user_id', name='uq_video_admin_chat_user')
    )
    op.create_index(op.f('ix_video_admins_chat_id'), 'video_admins', ['chat_id'], unique=False)
    op.create_index(op.f('ix_video_admins_user_id'), 'video_admins', ['user_id'], unique=False)
    op.create_table('call_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_title', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('media_type', sa.String(length=16), nullable=False),
    sa.Column('played_by', sa.BigInteger(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('helper_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['helper_account_id'], ['helper_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_reports_chat_id'), 'call_reports', ['chat_id'], unique=False)
    op.create_table('helper_chat_bindings',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('helper_account_id', sa.Integer(), nullable=False),
    sa.Column('bound_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['helper_account_id'], ['helper_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_index(op.f('ix_helper_chat_bindings_helper_account_id'), 'helper_chat_bindings', ['helper_account_id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=64), nullable=False),
    sa.Column('item_ref_id', sa.String(length=128), nullable=True),
    sa.Column('amount_irr', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_table('playback_states',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('helper_account_id', sa.Integer(), nullable=True),
    sa.Column('media_type', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('queue_position', sa.Integer(), nullable=False),
    sa.Column('seek_sec', sa.Integer(), nullable=False),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('last_update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['helper_account_id'], ['helper_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('sudo_wallets',
    sa.Column('sudo_user_id', sa.BigInteger(), nullable=False),
    sa.Column('balance_toman', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('locked_toman', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sudo_user_id'], ['sudos.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sudo_user_id')
    )
    op.create_table('sudo_wallet_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sudo_user_id', sa.BigInteger(), nullable=False),
    sa.Column('amount_toman', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('ref_type', sa.String(length=64), nullable=True),
    sa.Column('ref_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sudo_user_id'], ['sudo_wallets.sudo_user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sudo_wallet_transactions_sudo_user_id'), 'sudo_wallet_transactions', ['sudo_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sudo_wallet_transactions_sudo_user_id'), table_name='sudo_wallet_transactions')
    op.drop_table('sudo_wallet_transactions')
    op.drop_table('sudo_wallets')
    op.drop_table('playback_states')
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_helper_chat_bindings_helper_account_id'), table_name='helper_chat_bindings')
    op.drop_table('helper_chat_bindings')
    op.drop_index(op.f('ix_call_reports_chat_id'), table_name='call_reports')
    op.drop_table('call_reports')
    op.drop_index(op.f('ix_video_admins_user_id'), table_name='video_admins')
    op.drop_index(op.f('ix_video_admins_chat_id'), table_name='video_admins')
    op.drop_table('video_admins')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sudos_user_id'), table_name='sudos')
    op.drop_table('sudos')
    op.drop_index(op.f('ix_sudo_bulk_invoices_sudo_user_id'), table_name='sudo_bulk_invoices')
    op.drop_table('sudo_bulk_invoices')
    op.drop_index(op.f('ix_playlists_chat_id'), table_name='playlists')
    op.drop_table('playlists')
    op.drop_index(op.f('ix_player_vips_user_id'), table_name='player_vips')
    op.drop_index(op.f('ix_player_vips_chat_id'), table_name='player_vips')
    op.drop_table('player_vips')
    op.drop_index(op.f('ix_player_owners_user_id'), table_name='player_owners')
    op.drop_index(op.f('ix_player_owners_chat_id'), table_name='player_owners')
    op.drop_table('player_owners')
    op.drop_index(op.f('ix_owners_user_id'), table_name='owners')
    op.drop_table('owners')
    op.drop_index(op.f('ix_owner_sales_sudo_user_id'), table_name='owner_sales')
    op.drop_index(op.f('ix_owner_sales_owner_user_id'), table_name='owner_sales')
    op.drop_table('owner_sales')
    op.drop_index(op.f('ix_music_admins_user_id'), table_name='music_admins')
    op.drop_index(op.f('ix_music_admins_chat_id'), table_name='music_admins')
    op.drop_table('music_admins')
    op.drop_index(op.f('ix_invoices_chat_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_table('install_policy_settings')
    op.drop_index(op.f('ix_install_logs_chat_id'), table_name='install_logs')
    op.drop_table('install_logs')
    op.drop_index(op.f('ix_helper_accounts_phone'), table_name='helper_accounts')
    op.drop_table('helper_accounts')
    op.drop_index(op.f('ix_groups_chat_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_group_credits_chat_id'), table_name='group_credits')
    op.drop_table('group_credits')
    op.drop_table('free_install_whitelist')
    op.drop_index(op.f('ix_force_join_channels_channel_id'), table_name='force_join_channels')
    op.drop_table('force_join_channels')
    op.drop_index(op.f('ix_filter_words_word'), table_name='filter_words')
    op.drop_table('filter_words')
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_credit_history_invoice_id'), table_name='credit_history')
    op.drop_index(op.f('ix_credit_history_chat_id'), table_name='credit_history')
    op.drop_table('credit_history')
    op.drop_index(op.f('ix_chat_settings_chat_id'), table_name='chat_settings')
    op.drop_table('chat_settings')
    op.drop_index(op.f('ix_channels_chat_id'), table_name='channels')
    op.drop_table('channels')
    op.drop_table('bot_settings')
    op.drop_index(op.f('ix_blacklist_entity_id'), table_name='blacklist')
    op.drop_table('blacklist')
    # ### end Alembic commands ###
