#!/usr/bin/env python3
"""Build a clean deployment ZIP for manual SFTP upload (no secrets, no dev junk)."""

from __future__ import annotations

import argparse
import fnmatch
import re
import sys
import zipfile
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path, PurePosixPath

# ---------------------------------------------------------------------------
# Project layout (edit here when deploy roots change)
# ---------------------------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parent.parent

# Directories whose files are included (relative to project root).
INCLUDE_DIRS: tuple[str, ...] = ("app", "scripts", "deployment", "locales")

# Root-level files always included when present.
ROOT_INCLUDE_FILES: tuple[str, ...] = (
    "setup_server.sh",
    "requirements.txt",
    "pyproject.toml",
    "README.md",
    "LICENSE",
    # Multi-instance deployment: the runbook an operator needs on the server,
    # plus the simple Persian guide. musicbotctl is generated by the installer
    # and is deliberately not shipped (it embeds instance-specific paths).
    "docs/MULTI_INSTANCE_DEPLOYMENT.md",
    "docs/SIMPLE_MULTI_INSTANCE_GUIDE_FA.md",
    # Canonical env template. The real app/config.env is never packaged.
    "app/config.env.example",
    "config.env.example",
)

# Directory name segments that exclude a path anywhere under the tree.
EXCLUDED_DIR_NAMES: frozenset[str] = frozenset(
    {
        ".git",
        ".venv",
        "venv",
        ".graphify-venv",
        "__pycache__",
        ".pytest_cache",
        ".pytest-tmp",
        ".mypy_cache",
        ".ruff_cache",
        "dist",
        "build",
        "logs",
        "downloads",
        "media_cache",
        "sessions",
        ".cursor",
        ".vscode",
        "playwright-report",
        "test-results",
        ".playwright",
        "tests",
    }
)

# Playwright cache path segment (under .cache).
PLAYWRIGHT_CACHE_SEGMENT = ("ms-playwright",)

# Basename globs excluded at any depth.
EXCLUDED_FILE_GLOBS: tuple[str, ...] = (
    ".env",
    ".env.*",
    "*.env.bak*",
    "config.env",
    "config.env.bak*",
    "config.env.disposable",
    "app/config.env",
    "app/config.env.disposable",
    "*.session",
    "*.session-journal",
    "*.sqlite",
    "*.db",
    "*.db-shm",
    "*.db-wal",
    "*.log",
    "trace.zip",
    "*.trace.zip",
    "tg-vc-player-saas.zip",
    "fix_tests.py",
    "fix_tests_*.py",
    "patch_script.py",
    "patch_script*.py",
    "scratch_dump.txt",
    "scratch_dump_*.txt",
    "search_summary.txt",
    "*.webm",
)

ALLOWED_ENV_TEMPLATE_BASENAMES: frozenset[str] = frozenset(
    {
        "config.env.example",
        "config.env.disposable.example",
        "config.env.test.example",
    }
)

# Exact relative paths (POSIX, lowercased) that must never be packaged.
DANGEROUS_REL_PATHS: frozenset[str] = frozenset(
    {
        "app/config.env",
        "app/config.env.disposable",
        "config.env",
        "config.env.disposable",
        ".env",
    }
)

# Alembic head revision id (sanity check message only; migrations ship via app/).
EXPECTED_MIGRATION_HEAD = "0039_hot_seat"

PLACEHOLDER_MARKERS: tuple[str, ...] = (
    "CHANGE_ME",
    "change_me",
    "REPLACE",
    "replace",
    "changeme",
    "CHANGEME",
    "example",
    "EXAMPLE",
    "your_",
    "YOUR_",
    "placeholder",
    "PLACEHOLDER",
    "xxx",
    "XXX",
    "insert_",
    "INSERT_",
)

MAX_TEXT_SCAN_BYTES = 2 * 1024 * 1024

# Never content-scan these paths (docs or this script's own pattern literals).
CONTENT_SCAN_SKIP_REL: frozenset[str] = frozenset(
    {
        "scripts/build_deploy_zip.py",
    }
)

# Only scan content on env templates and app settings (not README/docs).
CONTENT_SCAN_SUFFIXES: frozenset[str] = frozenset(
    {".example", ".env", ".ini"},
)

CONTENT_SCAN_REL_EXACT: frozenset[str] = frozenset(
    {"app/config/settings.py"},
)


@dataclass
class BuildSummary:
    """Collect packaging statistics for the final report."""

    included: list[str] = field(default_factory=list)
    excluded: list[str] = field(default_factory=list)
    safety_errors: list[str] = field(default_factory=list)


def _posix_relpath(path: Path) -> str:
    """Return a normalized POSIX path relative to the project root."""
    rel = path.relative_to(PROJECT_ROOT)
    return PurePosixPath(rel.as_posix()).as_posix()


def _path_has_excluded_dir(rel_posix: str) -> bool:
    parts = PurePosixPath(rel_posix).parts
    if any(part in EXCLUDED_DIR_NAMES for part in parts):
        return True
    if ".cache" in parts and PLAYWRIGHT_CACHE_SEGMENT[0] in parts:
        return True
    return False


def _basename_excluded(name: str) -> bool:
    for pattern in EXCLUDED_FILE_GLOBS:
        if fnmatch.fnmatch(name, pattern):
            return True
    return False


def should_exclude_file(path: Path) -> bool:
    """Return True if this file must not be packaged."""
    rel = _posix_relpath(path)
    basename = path.name.lower()
    if _path_has_excluded_dir(rel):
        return True
    if rel.lower() in DANGEROUS_REL_PATHS:
        return True
    if (
        basename.startswith("config.env.")
        and basename not in ALLOWED_ENV_TEMPLATE_BASENAMES
    ):
        return True
    if basename.startswith(".env."):
        return True
    if _basename_excluded(path.name):
        return True
    return False


def should_exclude_dir(path: Path) -> bool:
    """Return True if this directory should not be walked."""
    rel = _posix_relpath(path)
    return _path_has_excluded_dir(rel)


def collect_root_files() -> list[Path]:
    """Collect explicit root-level include files."""
    files: list[Path] = []
    for rel in ROOT_INCLUDE_FILES:
        path = PROJECT_ROOT / rel
        if path.is_file() and not path.is_symlink():
            if should_exclude_file(path):
                continue
            files.append(path)
    return files


def collect_tree_files() -> list[Path]:
    """Walk include directories and collect files."""
    found: list[Path] = []
    for dir_name in INCLUDE_DIRS:
        base = PROJECT_ROOT / dir_name
        if not base.is_dir():
            continue
        for path in sorted(base.rglob("*")):
            if path.is_symlink():
                continue
            if path.is_dir():
                if should_exclude_dir(path):
                    continue
                continue
            if not path.is_file():
                continue
            if should_exclude_file(path):
                continue
            found.append(path)
    return found


def collect_candidates() -> list[Path]:
    """Build the sorted list of files to package."""
    paths = collect_root_files() + collect_tree_files()
    unique = {p.resolve(): p for p in paths}
    return sorted(unique.values(), key=lambda p: _posix_relpath(p))


def _is_placeholder_value(key: str, value: str) -> bool:
    """Heuristic: treat obvious template values as safe in .example files."""
    stripped = value.strip().strip('"').strip("'")
    if not stripped:
        return True
    if key in {"API_ID", "DEVELOPER_ID"} and stripped in {"0", "00000000"}:
        return True
    if key == "BOT_TOKEN" and stripped.lower() in {"test", "replace_with_bot_token"}:
        return True
    if key == "API_HASH" and stripped.lower() in {"testhash", "replace_with_api_hash"}:
        return True
    if any(marker in stripped for marker in PLACEHOLDER_MARKERS):
        return True
    if stripped.lower() in {"none", "null", "false", "true"}:
        return True
    if len(stripped) <= 4 and stripped.isdigit():
        return True
    return False


def _is_safe_dev_database_url(value: str) -> bool:
    """Allow documented local/disposable Postgres URLs in templates."""
    lower = value.lower()
    safe_bits = (
        "devpassword",
        "change-this",
        "replace",
        "localhost",
        "127.0.0.1",
        "musicbot_dev",
        "musicbot_disposable",
        "example",
    )
    return any(bit in lower for bit in safe_bits)


def _is_safe_dev_redis_url(value: str) -> bool:
    """Allow local Redis URLs in templates."""
    lower = value.lower()
    return any(
        bit in lower
        for bit in ("localhost", "127.0.0.1", "replace", "example", ":6380/")
    )


def _is_safe_helper_session_key(value: str) -> bool:
    """Allow empty or template helper session keys."""
    if not value.strip():
        return True
    return _is_placeholder_value("HELPER_SESSION_KEY_CURRENT", value)


def _line_has_secret(line: str, is_example: bool) -> str | None:
    """Return an error message if the line looks like a real secret."""
    stripped = line.strip()
    if not stripped or stripped.startswith("#"):
        return None
    if "=" not in stripped:
        return None
    key, _, value = stripped.partition("=")
    key = key.strip()
    value = value.strip()

    if key == "BOT_TOKEN":
        if is_example and _is_placeholder_value(key, value):
            return None
        if not is_example:
            return "forbidden BOT_TOKEN outside example files"
        return "non-placeholder BOT_TOKEN in example file"

    if key == "API_HASH":
        if is_example and _is_placeholder_value("API_HASH", value):
            return None
        if not is_example:
            return "forbidden API_HASH outside example files"
        return "non-placeholder API_HASH in example file"

    if key == "DATABASE_URL" and "postgresql" in value.lower():
        if is_example and _is_safe_dev_database_url(value):
            return None
        if not is_example:
            return "forbidden DATABASE_URL with postgresql outside example files"
        return "non-placeholder DATABASE_URL in example file"

    if key == "REDIS_URL" and value.lower().startswith("redis"):
        if is_example and _is_safe_dev_redis_url(value):
            return None
        if not is_example:
            return "forbidden REDIS_URL outside example files"
        return "non-placeholder REDIS_URL in example file"

    if key == "HELPER_SESSION_KEY_CURRENT":
        if is_example and _is_safe_helper_session_key(value):
            return None
        if not is_example:
            return "forbidden HELPER_SESSION_KEY_CURRENT outside example files"
        return "non-placeholder HELPER_SESSION_KEY_CURRENT in example file"

    return None


def _path_needs_content_scan(path: Path) -> bool:
    rel = _posix_relpath(path)
    if rel in CONTENT_SCAN_SKIP_REL:
        return False
    if rel in CONTENT_SCAN_REL_EXACT:
        return True
    if path.suffix.lower() in CONTENT_SCAN_SUFFIXES:
        return True
    return ".example" in path.name


def _should_scan_content(path: Path) -> bool:
    if not _path_needs_content_scan(path):
        return False
    try:
        return path.stat().st_size <= MAX_TEXT_SCAN_BYTES
    except OSError:
        return False


def scan_safety(candidates: list[Path]) -> list[str]:
    """Fail-fast checks before writing the ZIP."""
    errors: list[str] = []
    for path in candidates:
        rel = _posix_relpath(path)
        rel_lower = rel.lower()
        if rel_lower in DANGEROUS_REL_PATHS:
            errors.append(f"dangerous path scheduled for include: {rel}")
        if fnmatch.fnmatch(path.name.lower(), "*.session"):
            errors.append(f"session file scheduled for include: {rel}")
        if fnmatch.fnmatch(path.name.lower(), "*.session-journal"):
            errors.append(f"session journal scheduled for include: {rel}")

        if not _should_scan_content(path):
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError as exc:
            errors.append(f"cannot read {rel}: {exc}")
            continue

        is_example = rel_lower.endswith(".example") or ".example" in rel_lower
        for line in text.splitlines():
            issue = _line_has_secret(line, is_example)
            if issue:
                errors.append(f"{rel}: {issue}")
                break

        # Obvious live Telegram bot token shape (digits:alphanumeric)
        if not is_example:
            token_match = re.search(r"\b\d{8,12}:[A-Za-z0-9_-]{30,}\b", text)
            if token_match:
                errors.append(f"{rel}: possible live BOT_TOKEN pattern detected")

    return errors


def default_output_path() -> Path:
    """Timestamped zip under dist/."""
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    return PROJECT_ROOT / "dist" / f"musicbot-deploy-{stamp}.zip"


def write_zip(candidates: list[Path], output: Path, verbose: bool) -> None:
    """Write the deployment archive."""
    output.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(
        output,
        mode="w",
        compression=zipfile.ZIP_DEFLATED,
        compresslevel=6,
    ) as zf:
        for path in candidates:
            arcname = _posix_relpath(path)
            if verbose:
                print(f"  + {arcname}")
            zf.write(path, arcname)


def print_report(
    summary: BuildSummary,
    output: Path | None,
    dry_run: bool,
) -> None:
    """Print human-readable packaging summary."""
    print()
    print("=== Deployment ZIP build ===")
    print(f"Project root: {PROJECT_ROOT}")
    print(f"Expected Alembic head: {EXPECTED_MIGRATION_HEAD}")
    print(f"Mode: {'dry-run' if dry_run else 'write'}")
    print()
    print(f"Included files: {len(summary.included)}")
    if summary.included:
        show = (
            summary.included if len(summary.included) <= 40 else summary.included[:20]
        )
        for rel in show:
            print(f"  + {rel}")
        if len(summary.included) > 40:
            print(f"  ... and {len(summary.included) - 40} more")
    print()
    print(
        f"Excluded (sample): {min(len(summary.excluded), 30)} shown of {len(summary.excluded)}"
    )
    for rel in summary.excluded[:30]:
        print(f"  - {rel}")
    if len(summary.excluded) > 30:
        print(f"  ... and {len(summary.excluded) - 30} more excluded paths")
    print()
    if summary.safety_errors:
        print("SAFETY CHECK FAILED:")
        for err in summary.safety_errors:
            print(f"  ! {err}")
    elif output is not None and not dry_run:
        print(f"ZIP written: {output}")
        print(f"Size bytes: {output.stat().st_size}")
    elif dry_run:
        print("Dry-run complete; no ZIP written.")
    print()


def note_excluded_samples(summary: BuildSummary) -> None:
    """Record representative excluded paths for the report."""
    samples: list[str] = []
    for dir_name in ("dist", ".git", ".venv", "venv", "logs", "tests"):
        p = PROJECT_ROOT / dir_name
        if p.exists():
            samples.append(f"{dir_name}/ (directory excluded)")
    for pattern in (
        "app/config.env",
        ".env",
        "*.session",
        "__pycache__",
        "playwright-report",
    ):
        samples.append(f"pattern: {pattern}")
    summary.excluded.extend(samples)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parse CLI options."""
    parser = argparse.ArgumentParser(
        description="Build a clean deployment ZIP (no secrets, no dev artifacts).",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="Output zip path (default: dist/musicbot-deploy-YYYYMMDD-HHMMSS.zip)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Scan and report only; do not write a zip file.",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Print each file added to the archive.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Entry point."""
    args = parse_args(argv)
    summary = BuildSummary()
    note_excluded_samples(summary)

    candidates = collect_candidates()
    summary.included = [_posix_relpath(p) for p in candidates]

    migration_dir = PROJECT_ROOT / "app" / "database" / "migrations" / "versions"
    if migration_dir.is_dir():
        migration_count = len(list(migration_dir.glob("*.py")))
        if migration_count < 19:
            summary.safety_errors.append(
                f"expected migrations through {EXPECTED_MIGRATION_HEAD}; "
                f"found {migration_count} version files",
            )

    summary.safety_errors.extend(scan_safety(candidates))

    output = args.output
    if output is None and not args.dry_run:
        output = default_output_path()
    elif output is not None and not output.is_absolute():
        output = PROJECT_ROOT / output

    if summary.safety_errors:
        print_report(summary, None, args.dry_run)
        return 1

    if args.dry_run:
        print_report(summary, None, True)
        return 0

    assert output is not None
    write_zip(candidates, output, args.verbose)
    print_report(summary, output, False)
    print(f"Final zip path: {output.resolve()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
